defaults: &defaults
  adapter: solid_cable
  connects_to:
    database:
      writing: primary
      reading: primary
  polling_interval: 0.1.seconds
  message_retention: 1.day

development: *defaults
test:
  adapter: test
beta: *defaults
staging: *defaults
production: *defaults
